#
# version.cmake : version du projet
#

set (QWT_CHARTS_MAJOR_VERSION "5")
set (QWT_CHARTS_MINOR_VERSION "3")
set (QWT_CHARTS_RELEASE_VERSION "2")
set (QWT_CHARTS_VERSION ${QWT_CHARTS_MAJOR_VERSION}.${QWT_CHARTS_MINOR_VERSION}.${QWT_CHARTS_RELEASE_VERSION})


